# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9522cec270d7e8c6e2d5086289ff92805fd87cde35a58db60ff83f250760ff6d884615f2ddfc1dd4f5f387503ad53e8b0c6469960009ec865d4a302be23a4ad4

test:
  secret_key_base: 688ce7e4c931adec298156aa40359d1e43176afcd9f94d27d06fff1a978889c29ee3ad0d0a8aa6dcea71fddea4b3789cfae42a63a72a3a3c9dfac20841730d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
